name: Prevent Supabase Inactivity

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  ping-database:
    runs-on: ubuntu-latest
    steps:
      - name: Make an API request to Supabase
        run: |
          curl -X GET "https://qjrcnsemukctnkjkyfct.supabase.co" \
          -H "apikey: ${{ secrets.SUPABASE_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_KEY }}"
